#!/usr/bin/env python

from sys import stdout
from Bio import SeqIO, Seq
import warnings
from Bio import BiopythonWarning
warnings.simplefilter('ignore', BiopythonWarning)

InFile = raw_input("Please provide the name of a Fasta file:\n\n")
OutFile = '%s.translated' % InFile

with open(InFile, 'rU') as FastaFile:
    with open(OutFile, 'w') as FastaTranslated:
        stdout.write('Writing output to %s...\n' % OutFile)
        for record in SeqIO.parse(FastaFile, "fasta"):
            ReadFrame = -1
            while ReadFrame <= 1:
                ReadFrame += 1
                FastaTranslated.write('>%s_RF:%s\n%s\n' % (str(record.name), str(ReadFrame), \
                        Seq.Seq(str(record.seq[ReadFrame:])).translate()))

stdout.write('Done writing output to %s!\n' % OutFile)
